### DISCUSSION TITLE
Run spaceauth and get FASTLANE_SESSION on CI without UI.interactive

### DISCUSSION THREAD

**Discussion by lukaszgieraltowski** [fastlane/fastlane#17012] [Ideas]
Hi everyone :wave:

# Problem:
If I generate the `FASTLANE_SESSION` for different region locally than my CI machine works, the session will expire in 24h instead 30 days.
I'm not able to run `spaceauth` remotely because that command requires user interaction in the middle of the process (putting received SMS code).

## Docs:
That issue has been already described in [Fastlane docs:](https://docs.fastlane.tools/best-practices/continuous-integration/#security-code-and-session):
> An Apple ID session is only valid for a certain region, meaning if your CI system is in a different region than your local machine, you might run into issues

## Previous solution:
> Do not enable the two factor authentication on Apple ID used by CI.

It doesn't work since Apple forced two factor authentication for new Apple ID accounts.

## Proposed solution:
Create a job/pipeline on remote machine executing `spaceauth` from that machine region in two stages:

1. Request to get the SMS code.
2. Request to validate received code and get the `FASTLANE_SESSION`.

## POC:
I tested proposed solution on Azure DevOps Microsoft-hosted agents.
Well, the Microsoft don't guarantee the immutability of the region of remote machines ([source](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#networking)), but the session is not expiring anymore.

### How to execute POC:
1. Create a pipeline:
```
pool:
  vmImage: 'macos-latest'

trigger: none

steps:
- task: Bash@3
  displayName: 'Clone fork'
  inputs:
    targetType: 'inline'
    script: git clone https://github.com/lukaszgieraltowski/fastlane.git fastlane_fork

- task: Bash@3
  displayName: 'Change the branch'
  inputs:
    targetType: 'inline'
    workingDirectory: 'fastlane_fork'
    script: git checkout feature/allow-ci-to-use-spaceauth

- task: Bash@3
  displayName: 'Bundle install'
  inputs:
    targetType: 'inline'
    workingDirectory: 'fastlane_fork'
    script: bundle install

- task: Bash@3
  displayName: 'FASTLANE Login: If fastlane_sms_code was not provided: get the code, otherwise verify entered code.'
  env:
    FASTLANE_USER: $(fastlane_user)
    FASTLANE_PASSWORD: $(fastlane_password)
    SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER: $(fastlane_phone_number)
    SPACESHIP_2FA_SMS_CODE: $(fastlane_sms_code)
  inputs:
    targetType: 'inline'
    workingDirectory: 'fastlane_fork'
    script: bundle exec fastlane spaceauth
```
2. Set variables in that pipeline: `fastlane_user`, `fastlane_password`, `fastlane_phone_number`, `fastlane_sms_code` (empty)
3. Execute the pipeline receiving SMS code and Cancel the job.
4. Set the `fastlane_sms_code` with received code.
5. Re-run the job.
6. Copy the `FASTLANE_SESSION`.
