### DISCUSSION TITLE
Unity build with Github Action (iOS), code signing problem

### DISCUSSION THREAD

**Discussion by jjaine** [fastlane/fastlane#17458] [Q&A] [answered]
I'm trying to make a Unity project build in Github Action for iOS. I have problems with code signing. Automatic signing doesn't work and neither does the manual one. Here are the errors and configurations for both ways of signing:

Automatic signing, Fastfile build and sign config:
```
update_code_signing_settings(use_automatic_signing: 'true', 
                             path: "./Unity-iPhone/Unity-iPhone.xcodeproj",
                             team_id: <team-id>)
build_app(xcargs: "-allowProvisioningUpdates", # for build (not sure if this is needed or helps)
          export_xcargs: "-allowProvisioningUpdates", # for archive (not sure if this is needed or helps)
          project: "./Unity-iPhone/Unity-iPhone.xcodeproj")
```

The error from code signing:
```
Code Signing Error: There are no accounts registered with Xcode. Add your developer account to Xcode
Code Signing Error: No profiles for <bundle-id> were found:  Xcode couldn't find any iOS App Development provisioning profiles matching <bundle-id>.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 13.7'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 13.7'
```

Manual signing, Fastfile build and sign config:
```
update_code_signing_settings(use_automatic_signing: 'false', 
                             path: "./Unity-iPhone/Unity-iPhone.xcodeproj",
                             team_id: <team id>)
update_project_provisioning(profile: <development provisioning profile>,
                            xcodeproj: "./Unity-iPhone/Unity-iPhone.xcodeproj",
                            code_signing_identity: <App Store distribution identity>)
build_app(xcargs: "-allowProvisioningUpdates",
          export_xcargs: "-allowProvisioningUpdates", 
          project: "./Unity-iPhone/Unity-iPhone.xcodeproj",
          export_options: {
              signingStyle: "manual",
              provisioningProfiles: {
                  <bundle-id>: <App Store provisioning profile>
              }
          })
```
The error from the code signing:
```
Code Signing Error: UnityFramework does not support provisioning profiles. UnityFramework does not support provisioning profiles, but provisioning profile <development provisioning profile> has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.
```

I have tried countless combinations of the settings, so if someone could point me towards a working solution, that'd be great!

**Comment by jjaine** [comment, marked as answer]
Alright, found the solution myself after trying some combinations more! Here are the configs that worked for me:
```
update_code_signing_settings(use_automatic_signing: 'true', 
                             path: "./Unity-iPhone/Unity-iPhone.xcodeproj")
update_code_signing_settings(use_automatic_signing: 'false', 
                             path: "./Unity-iPhone/Unity-iPhone.xcodeproj",
                             team_id: <team-id>,
                             targets: 'Unity-iPhone',
                             code_sign_identity: 'iPhone Developer',
                             bundle_identifier: <bundle-id>)
update_project_provisioning(profile: <development provisioning profile>,
                            xcodeproj: "./Unity-iPhone/Unity-iPhone.xcodeproj",
                            code_signing_identity: 'iPhone Developer',
                            target_filter: '.*Unity-iPhone.*')
build_app(project: "./Unity-iPhone/Unity-iPhone.xcodeproj")
```
So the whole lane looks like this:
```
platform :ios do
  desc "Build and upload iOS build to TestFlight."
  lane :release do
  build_unity_ios # runs a bash script that builds the Unity project for iOS and returns the lisence
  increment_build_number(xcodeproj: "./Unity-iPhone/Unity-iPhone.xcodeproj")
  
  # get development certs
  get_certificates(development: 'true', keychain_path: '/Users/runner/Library/Keychains/build.keychain-db')       
  get_provisioning_profile(development: 'true')
  # also get app store cert
  get_certificates(keychain_path: '/Users/runner/Library/Keychains/build.keychain-db')
  get_provisioning_profile
  
  # For Github actions:
  update_code_signing_settings(use_automatic_signing: 'true', 
                               path: "./Unity-iPhone/Unity-iPhone.xcodeproj")
  update_code_signing_settings(use_automatic_signing: 'false', 
                               path: "./Unity-iPhone/Unity-iPhone.xcodeproj",
                               team_id: <team-id>,
                               targets: 'Unity-iPhone',
                               code_sign_identity: 'iPhone Developer',
                               bundle_identifier: <bundle-id>)
  update_project_provisioning(profile: <development provisioning profile>
                              xcodeproj: "./Unity-iPhone/Unity-iPhone.xcodeproj",
                              code_signing_identity: 'iPhone Developer',
                              target_filter: '.*Unity-iPhone.*')
  build_app(project: "./Unity-iPhone/Unity-iPhone.xcodeproj")
  upload_to_testflight(skip_waiting_for_build_processing: 'true')
  end
end
```

In addition, the action uses https://github.com/sttz/install-unity to install Unity and creates a new keychain into which the development and distribution certs are installed.
```
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create new keychain
        run: security create-keychain -p <password> build.keychain && security default-keychain -s build.keychain

      - name: Set longer lock time for keychain
        run: security set-keychain-settings -lut 60000 build.keychain

      - name: Install signing cert
        run: security unlock-keychain -p <password> build.keychain && security add-certificate <distribution cert>

      - name: Install signing key
        run: security unlock-keychain -p <password> build.keychain && security import <distribution key> -k build.keychain -P <password> -A

      - name: Install dev cert
        run: security unlock-keychain -p <password> build.keychain && security add-certificate <development cert>

      - name: Install dev key
        run: security unlock-keychain -p <password> build.keychain && security import <development key> -k build.keychain -P <password> -A

      - name: Allow codesign to access dev key
        run: security unlock-keychain -p <password> build.keychain && security set-key-partition-list -S 'apple-tool:,apple:,codesign:' -s -k <password> build.keychain

      - name: Install fastlane
        run: sudo gem install fastlane -NV

      - name: Setup fastlane
        run: sudo bundle install

      - name: Unity setup tool
        run: brew cask install sttz/tap/install-unity

      - name: Unity setup
        run: sudo install-unity install <unity version> -y -p Unity iOS Android

     - name: Build and upload for Android
        run: bundle exec fastlane android release
        env:
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
            UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

      - name: Build and upload for iOS
        run: bundle exec fastlane ios release
        env:
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
            UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
            FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}
            FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
            FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
```
Hope this helps someone battling similar issues!
