### DISCUSSION TITLE
How to publish to custom closed track names

### DISCUSSION THREAD

**Discussion by danielmessi13** [fastlane/fastlane#17648] [Q&A]
Hello, I am currently configuring my project to do the automatic deployment, I am using Github Actions + Fastlane, I currently have several active tracks within the closed testing area of my application, I want to know how do I release a version just for one of the tracks.

In that [issue](https://github.com/fastlane/fastlane/pull/12487) the implementation is done but it does not say how do I use it

For example:

Closed tests:

- Active ranges:

1. Testers Group 1 
2. Testers Group 2 

My fastlane configuration in my flow looks like this:

```       
        - name: Setup Ruby
          uses: actions/setup-ruby@v1
          with:
            ruby-version: '2.6'

        - name: Cache bundle dependencies
          uses: actions/cache@v2
          with:
            path: vendor/bundle
            key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
            restore-keys: ${{ runner.os }}-gems-

        - name: Download bundle dependencies
          run: |
            gem install bundler:2.0.2
            bundle config path vendor/bundle
            bundle install
        - name: Release to Google Play (beta)
          env:
            SUPPLY_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME }}
            SUPPLY_JSON_KEY_DATA: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          run: |
            bundle exec fastlane supply \
            --aab build/app/outputs/bundle/release/app-release.aab \
            --track beta
```
