### DISCUSSION TITLE
For the `download_dsyms` action I am unable to authenticate on GitHub actions

### DISCUSSION THREAD

**Discussion by tahirmt** [fastlane/fastlane#17683] [Q&A] [answered]
Hi everyone I am using the `download_dsyms` lane to download and upload dsyms to Crashlytics. I wanted to add it into a GitHub Action but I can't seem to get authentication working. First, I was using the `FASTLANE_SESSION` environment variable and I was getting an error of missing password. Then, I generated a one time password and stored it in `FASTLANE_PASSWORD` environment variable. Now I get invalid password error

`Invalid username and password combination. Used '<redacted>' as the username.
32`

I have my action set up like follows

```
- name: Upload dSYMs to crashlytics
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        run: |
          bundle exec fastlane upload_dsyms
```

and my lane is as follows to download files for the last 24 hours

```
desc "Upload dSYMs"
lane :upload_dsyms do 
  yesterday = DateTime.now - 1
  download_dsyms(after_uploaded_date: yesterday.iso8601)
  upload_symbols_to_crashlytics
  clean_build_artifacts
end
```
