### DISCUSSION TITLE
Need help for setting up fastlane match

### DISCUSSION THREAD

**Discussion by ji-denizturgut** [fastlane/fastlane#17768] [Q&A]
I'm trying to use GitHub action with fastlane to deploy build to TestFlight. So far I did the `match init` and match `development` created passphrase with private repo. I got the error under: 

> **INFO [2020-12-10 05:49:21.61]: ▸ git@github.com: Permission denied (publickey).
107
INFO [2020-12-10 05:49:21.61]: ▸ fatal: Could not read from remote repository.
108
INFO [2020-12-10 05:49:21.61]: ▸ Please make sure you have the correct access rights
109
INFO [2020-12-10 05:49:21.61]: ▸ and the repository exists.**

```
## Fastfile
default_platform(:ios)

platform :ios do
  
  def install_pods
   cocoapods(
      podfile: "./Podfile",
      try_repo_update_on_error: true
      )
  end
  
  desc "Create ipa"
  lane :build do
    install_pods()
    increment_build_number(xcodeproj: "appName.xcodeproj")
    build_app(workspace: "appName.xcworkspace", scheme: "Development")
    upload_to_testflight()
  end
  
  desc "Upload to App TestFlight"
  lane :upload do
    upload_to_testflight(
    	app_identifier: "com.appName",
    	ipa: "./fastlane/builds/Development.ipa",
        skip_waiting_for_build_processing: true
    	)
  end
end
```

```
##.yam file

name: fastlane
 
on: [push]
 
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Run fastlane setup
      env:
        APPLE_ACCOUNT: ${{ secrets.APPLE_ACCOUNT }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
      run: |
        sudo gem install bundler
    
    - name: Run fastlane build
      env:
        MATCH_REPO: ${{ secrets.MATCH_REPO }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}
        SIGNING_ID: ${{ secrets.SIGNING_ID }}
        APPLE_ACCOUNT: ${{ secrets.APPLE_ACCOUNT }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
      run: |
        bundle exec fastlane build --verbose
        
    - name: Run fastlane upload
      env:
        APPLE_ACCOUNT: ${{ secrets.APPLE_ACCOUNT }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
      run: fastlane upload --verbose

```

```
## Matchfile
ENV['MATCH_APP_IDENTIFIER'] = "com.appName"
git_url("git@github.com:xxxxxxx.git")
storage_mode("git")
type("development") # The default type, can be: appstore, adhoc, enterprise or development
shallow_clone true
force_for_new_devices true
```
