### DISCUSSION TITLE
Github Actions: No code signing identity found and can not create a new one because you enabled `readonly`

### DISCUSSION THREAD

**Discussion by aprilmintacpineda** [fastlane/fastlane#18272] [Q&A] [answered]
- This is my first time using fastlane and also using it with github actions.
- I'm using react-native

### What I am trying to do

I'm trying to use github actions to automate the building and deployment to testflight (and also google internal track after this).

### What I have done

I have been able to run fastlane deployment on my macbook for several releases in the past weeks, but I can't make it work on github actions, I've been able to make modifications to take it this far.

### The error currently I'm trying to solve

```
[10:26:48]: Cloning remote git repo...
[10:26:48]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[10:26:50]: Checking out branch master...
[10:26:50]: 🔓  Successfully decrypted certificates repo
[10:26:50]: Couldn't find a valid code signing identity for development... creating one for you now
+-----------------------------------+-----------------------------------------------------+
|                                      Lane Context                                       |
+-----------------------------------+-----------------------------------------------------+
| DEFAULT_PLATFORM                  | ios                                                 |
| PLATFORM_NAME                     | ios                                                 |
| LANE_NAME                         | ios dev                                             |
| KEYCHAIN_PATH                     | ~/Library/Keychains/fastlane_tmp_keychain           |
| ORIGINAL_DEFAULT_KEYCHAIN         | "/Users/runner/Library/Keychains/login.keychain-db" |
| GET_INFO_PLIST_VALUE_CUSTOM_VALUE | 37                                                  |
+-----------------------------------+-----------------------------------------------------+
[10:26:50]: No code signing identity found and can not create a new one because you enabled `readonly`
```

#### Folder structure

```
/ root
| - fastlane <--- this is where all fastlane files are in
|   | - Appfile
|   | - Fastfile
|   | - Matchfile
|   | - Pluginfile
|   | - README.md <-- created by fastlane
| - ios
| - android
| - src
| - node_modules
| - package.json
```

**github workflow yaml file**

```yaml
name: ios-testflight-deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    continue-on-error: false
    env:
      MATCH_PASSWORD: password

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.MATCH_REPO_KEY }}
      
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Versions
        run: |
          echo "Yarn: $(yarn --version)"
          echo "Node: $(node --version)"
          echo "Ruby: $(ruby --version)"
          echo "Bundler: $(bundle --version)"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Setup dependencies
        run: |
          yarn
          npx pod-install
          echo "${{ secrets.myAuthKey }}" > myAuthKey.p8

      - name: Fastlane
        run: |
          ls -lha
          bundle exec fastlane ios dev
```

**Appfile**

```ruby
app_identifier("<hidden value>") # The bundle identifier of your app
apple_id("<hidden value>") # Your Apple email address

itc_team_id("<hidden value>") # App Store Connect Team ID
team_id("<hidden value>") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile
```

**Fastfile**

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :dev do
    begin
      setup_ci

      process_start_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)
      # slack_url = "<hidden value>"
      info_plist_path = "ios/my_app/Info.plist"
      version = get_info_plist_value(path: info_plist_path, key: "CFBundleShortVersionString")
      build_number = get_info_plist_value(path: info_plist_path, key: "CFBundleVersion")
      groups = ["App Store Connect Users"]

      api_key = app_store_connect_api_key(
        key_id: "<hidden value>",
        issuer_id: "<hidden value>",
        key_filepath: "myAuthKey.p8",
        in_house: true
      )

      match(api_key: api_key)

      # slack(
      #   message: "iOS: build has started for v#{version}(#{build_number})\n" +
      #     "Groups: #{groups.join(", ")}",
      #   slack_url: slack_url
      # )

      changelog = read_changelog(
        changelog_path: "CHANGELOG.md",
        section_identifier: "[#{version}]"
      )

      build_start_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)

      build_app(
        workspace: "ios/my_app.xcworkspace",
        scheme: "staging",
        clean: true,
        configuration: 'StagingRelease'
      )

      build_end_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)
      total_build_seconds = build_end_time - build_start_time
      build_minutes = total_build_seconds / 60
      build_seconds = total_build_seconds % 60

      # slack(
      #   message: "iOS: build completed for v#{version}(#{build_number}). Now uploading to testflight.",
      #   slack_url: slack_url
      # )

      upload_start_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)

      upload_to_testflight(api_key: api_key, groups: groups, changelog: changelog)
      clean_build_artifacts

      upload_end_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)
      total_upload_seconds = upload_end_time - upload_start_time
      upload_minutes = total_upload_seconds / 60
      upload_seconds = total_upload_seconds % 60

      process_end_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)
      total_process_seconds = process_end_time - process_start_time
      total_minutes = total_process_seconds / 60
      total_seconds = total_process_seconds % 60

      # slack(
      #   message: "iOS: successfully uploaded v#{version}(#{build_number}) to testflight.\n\n" +
      #   "Build Time: #{build_minutes.floor}:#{build_seconds.floor}\n" +
      #   "Upload Time: #{upload_minutes.floor}:#{upload_seconds.floor}\n" +
      #   "Total time: #{total_minutes.floor}:#{total_seconds.floor}\n" +
      #   "Groups: #{groups.join(", ")}",
      #   slack_url: slack_url
      # )
    rescue => error
      # slack(
      #   message: "Building failed:\n\n```\n#{error}```\n",
      #   slack_url: slack_url,
      #   success: false
      # )

      raise error
    end
  end
end
```

**Match file**

```ruby
git_url("<hidden value>")

storage_mode("git")

type("appstore") # The default type, can be: appstore, adhoc, enterprise or development

# app_identifier(["tools.fastlane.app", "tools.fastlane.app2"])
username("<hidden value>") # Your Apple Developer Portal username

# For all available options run `fastlane match --help`
# Remove the # in the beginning of the line to enable the other options

# The docs are available on https://docs.fastlane.tools/actions/match
```
