### DISCUSSION TITLE
Looking for advise on Github Actions

### DISCUSSION THREAD

**Discussion by aprilmintacpineda** [fastlane/fastlane#18482] [General]
**Fastfile**

```ruby
######## IOS CONFIGURATIONS
# If you want to make the build automatically available to external groups,
# add the name of the group to the array below, after "App Store Connect Users"
groups = ["App Store Connect Users"]
workspace = "my-app.xcworkspace"

# If you build for multiple environments, you might wanna set this specifically on build_app
configuration = 'Release'
scheme = "Production"

key_id = ENV["APPSTORE_KEY_ID"] # The key id of the p8 file
issuer_id = ENV["APPSTORE_ISSUER_ID"] # issuer id on appstore connect
key_filepath = "FastlaneDeploymentCI.p8" # The path to p8 file generated on appstore connect
######## END IOS CONFIGURATIONS

default_platform(:ios)

platform :ios do
  desc "Push a new build to TestFlight"

  lane :preprod do
    setup_ci

    api_key = app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_filepath: key_filepath,
      in_house: true
    )

    match(api_key: api_key)

    build_app(
      workspace: workspace,
      scheme: scheme,
      configuration: configuration,
      clean: true,
      silent: true
    )

    upload_to_testflight(
      api_key: api_key,
      groups: groups,
      skip_waiting_for_build_processing: true
    )

    clean_build_artifacts
  end
end
```

**Github Action**

```yaml
name: dev-ios-deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  release:
    types: [released]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    continue-on-error: false
    env:
      STAGE: <hidden value>
      API_BASE_URL: "<hidden value>"
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
      APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      ITUNES_TEAM_ID: ${{ secrets.ITUNES_TEAM_ID }}
      APPSTORE_TEAM_ID: ${{ secrets.APPSTORE_TEAM_ID }}
      MATCH_REPO_SSH: ${{ secrets.MATCH_REPO_SSH }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.MATCH_REPO_KEY }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Versions
        run: |
          echo "Yarn: $(yarn --version)"
          echo "Node: $(node --version)"
          echo "Ruby: $(ruby --version)"
          echo "Bundler: $(bundle --version)"

      - name: Install node modules
        run: yarn --prefer-offline

      - name: Install cocoapods
        run: |
          cd ios
          pod install

      - name: Bundle mainjs
        run: |
          cp src/env.example.js src/env.js
          NODE_ENV=production yarn bundle-js

      - name: Setup files
        run: |
          echo "${{ secrets.P8_AUTH_KEY }}" > ios/FastlaneDeploymentCI.p8
          echo "${{ secrets.GOOGLE_SERVICES_PLIST }}" > ios/proj_pronetplat_aa/GoogleService-Info.plist

      - name: Build and deploy
        run: |
          cd ios
          NODE_ENV=production bundle exec fastlane ios preprod
```

**Error**

```
[!] Error uploading ipa file: 
+------+---------------------------+-------------+
 [Transporter Error Output]: ERROR ITMS-90704: Missing App Icon. An app icon measuring 1024 by 1024 pixels in PNG format must be included in the Asset Catalog of apps built for iOS, iPadOS, or watchOS. Without this icon, apps cannot be submitted for review. For details, see https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/.
```

When I use GitHub actions to deploy react-native ios, it always finds a way to stumble and fail. I ran the same exact commands on my machine, and it worked perfectly. I do have the App Icon setup and this isn't really the first deployment, so I don't know what this guy is complaining about.

Before this error, I encountered an error with Authentication, it said:

```
[12:53:12]: Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
```

So all I did was update the secrets which were updated 25 days ago and put in the same exact values as before, and then that somehow fixed the error, what gives?

Then now this error. The bad thing is, every time it fails, I need to re-run it and it takes 30 minutes again, only to fail again, and it gets really expensive and annoying.

The more complex my app gets, the more error I get, but again, this isn't cheap, 1 MacOS minute is 10 regular minutes in Github actions, which is insane.

Is GitHub actions really worth it?
