### DISCUSSION TITLE
Support for google-github-actions/auth

### DISCUSSION THREAD

**Discussion by eriksw** [fastlane/fastlane#19869] [Ideas] [answered]
For security reasons, we don't want to create service account keys. We have an organization-level policy set in Google Cloud to **prevent** service account key creation and instead use instance credentials and [Workload Identity Federation](https://cloud.google.com/iam/docs/workload-identity-federation) exclusively.

We want to have our beta push workflow use credentials obtained using https://github.com/google-github-actions/auth but run into `missing client_email` error.

Our Github Actions step to obtain credentials looks like:

```
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          create_credentials_file: true
          project_id: 'REDACTED'
          service_account: 'REDACTED@REDACTED.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/REDACTED/locations/global/workloadIdentityPools/REDACTED/providers/REDACTED'
```

Important: These kinds of credentials work perfectly for interacting with Google Cloud using `gcloud`, the Google Cloud SDK for Go, and many other tools. **Fastlane is an outlier for not working with them.**

Note: It appears that the `googleauth` library already has support for working with an externally-obtained oauth2 token, so this shouldn't require changes outside of fastlane: https://github.com/googleapis/google-auth-library-ruby/issues/346 

<details>
<summary>The full error we encounter</summary>

```
[09:52:29]: ---------------------------------------
[09:52:29]: --- Step: firebase_app_distribution ---
[09:52:29]: ---------------------------------------
[09:52:29]: Authenticating with GOOGLE_APPLICATION_CREDENTIALS environment variable: /home/runner/work/_temp/1c99ce16294bf5ea288530f3
+-------------------------------------+----------------------------------------------------------------------------------------------------------------------------+
|                                                                           Lane Context                                                                           |
+-------------------------------------+----------------------------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                    | android                                                                                                                    |
| PLATFORM_NAME                       | android                                                                                                                    |
| LANE_NAME                           | android beta                                                                                                               |
| GRADLE_ALL_APK_OUTPUT_PATHS         | ["/home/runner/work/REDACTED/***/build/outputs/apk/release/***-release.apk"] |
| GRADLE_ALL_AAB_OUTPUT_PATHS         | []                                                                                                                         |
| GRADLE_ALL_OUTPUT_JSON_OUTPUT_PATHS | ["/home/runner/work/REDACTED/***/build/outputs/apk/release/output-metadata.json"]   |
| GRADLE_ALL_MAPPING_TXT_OUTPUT_PATHS | ["/home/runner/work/REDACTED/***/build/outputs/mapping/release/mapping.txt"]        |
| GRADLE_APK_OUTPUT_PATH              | /home/runner/work/REDACTED/***/build/outputs/apk/release/***-release.apk     |
| GRADLE_OUTPUT_JSON_OUTPUT_PATH      | /home/runner/work/REDACTED/***/build/outputs/apk/release/output-metadata.json       |
| GRADLE_MAPPING_TXT_OUTPUT_PATH      | /home/runner/work/REDACTED/***/build/outputs/mapping/release/mapping.txt            |
+-------------------------------------+----------------------------------------------------------------------------------------------------------------------------+
[09:52:29]: missing client_email

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | Verifying fastlane version                                    | 0           |
| 2    | default_platform                                              | 0           |
| 3    | Switch to android increment_version_number_android_if_needed  | 0           |
| 4    | Switch to android calculate_version lane                      | 0           |
| 5    | Switch to android increment_build_number_android lane         | 0           |
| 6    | Switch to android commit_version_bump_android lane            | 0           |
| 7    | git_add                                                       | 0           |
| 8    | git_commit                                                    | 0           |
| 9    | add_git_tag                                                   | 0           |
| 10   | assembleRelease                                               | 304         |
| 💥   | firebase_app_distribution                                     | 0           |
+------+---------------------------------------------------------------+-------------+

[09:52:29]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  (supply): Could not find option 'key' in the list of available options: json_key, json_key_data, root_url, timeout
    https://github.com/fastlane/fastlane/issues/18338 [closed] 1 💬
    05 May 2021

➡️  Neither PUB key nor PRIV key: not enough data
    https://github.com/fastlane/fastlane/issues/11040 [closed] 1 💬
    28 Jan 2018

➡️  supply init returns that client_email is missing.
    https://github.com/fastlane/fastlane/issues/4751 [closed] 1 💬
bundler: failed to load command: fastlane (/home/runner/work/REDACTED/vendor/bundle/ruby/2.6.0/bin/fastlane)
    24 Nov 2016
/home/runner/work/REDACTED/vendor/bundle/ruby/2.6.0/gems/googleauth-1.1.0/lib/googleauth/json_key_reader.rb:24:in `read_json_key': [!] missing client_email (RuntimeError)

    from /home/runner/work/REDACTED/vendor/bundle/ruby/2.6.0/gems/googleauth-1.1.0/lib/googleauth/service_account.rb:56:in `make_creds'
and 1 more at: https://github.com/fastlane/fastlane/search?q=missing%20client_email&type=Issues&utf8=✓
    from /home/runner/work/REDACTED/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.3.2/lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_auth_client.rb:81:in `service_account'

    from /home/runner/work/REDACTED/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.3.2/lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_auth_client.rb:35:in `fetch_auth_token'
    from /home/runner/work/REDACTED/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.3.2/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:30:in `run'
    from /home/runner/work/REDACTED/vendor/bundle/ruby/2.6.0/gems/fastlane-2.202.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
    from /home/runner/work/REDACTED/vendor/bundle/ruby/2.6.0/gems/fastlane-2.202.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
    ...
```
</details>

**Comment by trenslow** [comment]
did anyone ever figure out how to do this? it seems like the ruby google auth library supports WIF now: https://github.com/googleapis/google-auth-library-ruby/pull/418., but its not clear to me if fastlane will support the credentials obtained via WIF in a previous action step

**Comment by BramMusters** [comment]
Any news? This seems to be the most secure way to handle beta pushes to Firebase App Distribution.

**Comment by sanlanka** [comment]
Any updates on this? Is there even a plan to work on it? 
I have match that uses GCP and the service account has full access to read and write to the bucket.

**Comment by mataku** [comment]
created a pull request for supply actions: https://github.com/fastlane/fastlane/pull/27949

- - -

firebase-app-distribution fastlane plugin already supports Workload Identity Federation, so we could use it without any fastlane changes.
https://github.com/firebase/fastlane-plugin-firebase_app_distribution

**Comment by trenslow** [comment, marked as answer]
i can confirm this has been working since fastlane 2.232.0

heres an example thats tried and tested on my side:

```yaml
      - name: Authenticate with Google Cloud
        id: auth-gcp
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{ vars.GCP_WI_PROVIDER }}
          service_account: ${{ vars.GCP_WI_SVC_ACCT }}
          create_credentials_file: true
      - name: Upload to Google Play
        run: |
          fastlane supply \
              < extra config here >
              --json_key '${{ steps.auth-gcp.outputs.credentials_file_path }}'
```

hope this helps later visitors to this thread!
