### DISCUSSION TITLE
Use Fastlane with gitlab

### DISCUSSION THREAD

**Discussion by talbiislam96** [fastlane/fastlane#20162] [Q&A]
I am new to ci/cd , I have installed Fastlane in my flutter project added fast files , gem files ... to both android and iOS.
am trying to get GitLab CI to run the following script when I push on my my brach : 
``` 
flutter_increment_app_version: 
  dependencies: []
  stage: versionning 
  script:
    - cd android/
    - fastlane bump_minor
    - fastlane apply_new_version
    - fastlane read_version
    
  only:
    - feature/versionningApp


```
but I get the following error : 

``` 
/usr/bin/bash: line 129: fastlane: command not found

```
 what should I do to fix this please been stuck for a while now . would be grateful for your help
