### DISCUSSION TITLE
Proposing action to upload Android symbols to Crashlytics

### DISCUSSION THREAD

**Discussion by ivribalko** [fastlane/fastlane#20230] [Show and tell]
Hello!

As per

>Please be aware we may not accept all actions submitted to be bundled with fastlane. Before you submit a pull request adding the action to the fastlane code base, submit an issue proposing the new action and why it should be built-in.

I'd like to suggest an action to upload Android symbols to Crashlytics.

Some facts:
- There is existing https://docs.fastlane.tools/actions/upload_symbols_to_crashlytics/ action already however it is iOS only.
- I'm not sure if that's a Unity thing only but here's from https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=unity#ios:
>For Apple platform apps using the Crashlytics Unity SDK 8.2.0+, the Firebase Unity Editor plugin automatically configures your Xcode project to upload symbols
- Uploading Android symbols is still required though which this action is about, see https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=unity#android
- The proposed action confirmed to enhance crash reports.
- The proposed action confirmed to work in GitHub Actions.
- The proposed action confirmed to work for Unity projects.

Here's the action: https://gist.github.com/ivribalko/239b4c36180f122a659e4c1d4a12f6f8

I think it could be useful for fastlane to host both iOS and Android action for that purpose.

Thanks!

**Comment by anatoliisudor** [comment]
+1 to this request.
For now it can be implemented with system call only like this:
`system("firebase crashlytics:symbols:upload --app=#{firebaseAppId} ../build/app/obfuscation/#{flavor}/")`

**Comment by kevinetore** [comment]
As the actions https://github.com/vimtor/action-setup-firebase and https://github.com/w9jds/firebase-action did not completely work for my use-case (archived project and couldn't get firebase-action to work specifically for Crashlytics). I ended up with:

```yml
# Install the Firebase CLI in order to perform crashlytics operations
- name: Install Firebase CLI
  run: |
    curl -sL https://firebase.tools | bash
# Firebase CLI token from login CLI command
# Retrieve Firebase Android app ID from Firebase GUI console
- name: Deploy symbols to Firebase Crashlytics
  run: |
    firebase --token="${{ secrets.FIREBASE_CLI_TOKEN }}" crashlytics:symbols:upload --app="${{ secrets.FIREBASE_ANDROID_APP_ID }}" ./build/app/outputs/bundle/release/symbols
```

Hopefully it helps someone.
