### DISCUSSION TITLE
Is there a required naming convention when accessing custom variables in a CI server using `ENV`?

### DISCUSSION THREAD

**Discussion by dustincatap** [fastlane/fastlane#20335] [Q&A]
I have setup a build pipeline in Azure DevOps and defined a variable:

```yml
variables:
  - name: AppEnvironment
    value: dev
```

And in my Fastfile, I set another variable from the one above:

```ruby

app_environment = ""

before_all do
  app_environment = ENV["AppEnvironment"]

  if app_environment.nil? || app_environment.empty?
    UI.user_error! "Please provide a value for `AppEnvironment`"
  end
end
```

But it seems that Fastlane cannot retrieve the value. 

I also wrote-out the variables of `ENV` and confirmed that `AppEnvironment` is existing and has value.

```ruby
lane :"get_env_values" do |options|
  puts "`ENV` values"
  ENV.each { |k, v| puts "#{k}: #{v}" }
end
```

I tried changing the naming of my variable in Azure:

```yml
variables:
  - name: APP_ENVIRONMENT
    value: dev
```

Then accessing this in Fastlane using `ENV["APP_ENVIRONMENT"]` returns the expected value.

Is this behavior expected?
