### DISCUSSION TITLE
ERROR ITMS-90189: Redundant Binary Upload - but only on CI

### DISCUSSION THREAD

**Discussion by joemasilotti** [fastlane/fastlane#20401] [Q&A]
Hi there, I'm trying to automate TestFlight build uploads for my app. I have everything working locally, but when I run the same lane on CI (GitHub Actions) I get the following error:

> [16:46:20]: [iTMSTransporter] 		ERROR ITMS-90189: "Redundant Binary Upload. You've already uploaded a build with build number '1' for version number '1.0'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4)."

### Fastfile

```ruby
# fastlane/Fastfile

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    if ENV["CI"]
      setup_ci
      app_store_connect_api_key
    end

    run_tests

    sync_code_signing
    build_app
    upload_to_testflight
  end
end
```

### GitHub Action configuration

```yaml
# .github/workflows/release.yml

name: Release

on:
  push:
    branches:
      - main
      - ci

jobs:
  fastlane:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: default
          bundler-cache: true

      - name: Run tests and upload build to TestFlight
        run: bundle exec fastlane ios release
        env:
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_TYPE: appstore
          FASTLANE_SKIP_UPDATE_CHECK: true
```

I'm using `fastlane (2.206.2)`.

Running `bundle exec fastlane ios release` locally works fine. Am I missing something obvious? Or is `setup_ci` doing something to mess with the automated version bumping?

Any help would be greatly appreciated!
