### DISCUSSION TITLE
Fastlane with latest mac OS can't find temp keychain created. Github actions

### DISCUSSION THREAD

**Discussion by Epiclemonaid** [fastlane/fastlane#21015] [General]
it appears that fastlane can't find the keychain I'm creating even though it loads in the env variables and lists the keychain above
![image](https://user-images.githubusercontent.com/11666664/215292211-7e0c648a-93d6-411d-be07-5b3c5b999e6b.png)

```
default_platform(:ios)

DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]
DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("/Users/runner/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: "name",
    password: "password",
    default_keychain: true,
    unlock: true,
    timeout: 360000,
    lock_when_sleeps: false
    add_to_search_list: true
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  lane :closed_beta do
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_temp_keychain(keychain_name, keychain_password)

    match(
      type: 'appstore',
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      readonly: true,
      keychain_name: "login",
      keychain_password: keychain_password
    )

    gym(
      configuration: "Release",
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
            DEVELOPER_APP_ID => PROVISIONING_PROFILE_SPECIFIER
        }
      }
    )

    pilot(
      apple_id: "#{DEVELOPER_APP_ID}",
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      skip_waiting_for_build_processing: false,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "./Runner.ipa"
    )

    delete_temp_keychain(keychain_name)
  end
end
```

I've tried everything and nothing works. changing the name listing the keychains in that location. and disabling it completely 

```
name: (IOS) Build and release workflow for dev/testing

on:
  push:
    branches:
      - 'release/*-prod'

jobs:
  build-release-ios-dev:
    runs-on: macos-latest
    environment: prod
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: 2.8.1
        channel: 'stable'
        architecture: x64
        working-directory: ios

    - run: flutter doctor -v
    - run: flutter pub get
    # - run: flutter test #will un-comment this once we have added unit test on the project
    - run: flutter analyze #check for linter errors or warnings
    - run: flutter build ios --release --no-codesign
      env:
        IPHONEOS_DEPLOYMENT_TARGET: 14.0

    - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
    - run: ls -lah ~/.ssh/
    - run: security find-certificate -a
    - run: security find-identity -v -p codesigning

    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: Carketa-Inc/certificates
        path: certificates
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - run: ls ~/Library/Keychains/
    - run: security find-certificate -a -c 'Apple Worldwide Developer Relations' -p /Users/runner/Library/Keychains/login.keychain-db

    - name: Deploy iOS Beta to TestFlight via Fastlane
      uses: maierj/fastlane-action@v2.0.0
      with:
        lane: closed_beta
        subdirectory: ios
      env:
        SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER: '${{ secrets.SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER }}'
        FASTLANE_PASSWORD: '${{ secrets.FASTLANE_PASSWORD }}'
        APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
        DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
        DEVELOPER_APP_IDENTIFIER: '${{ secrets.DEVELOPER_APP_IDENTIFIER }}'
        DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
        FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
        MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
        GIT_AUTHORIZATION: '${{ vars.GIT_AUTHORIZATION }}'
        PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
        TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
        TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
        SSH_PRIVATE_KEY: '${{ secrets.SSH_PRIVATE_KEY }}'

```

error message:

```
[20:05:31]: Could not locate the provided keychain. Tried:
	/Users/runner/Library/Keychains/***-db
	/Users/runner/Library/Keychains/***.keychain-db
	/Users/runner/Library/Keychains/***
	/Users/runner/Library/Keychains/***.keychain
	/Users/runner/work/CarketaV2/CarketaV2/ios/***-db
	/Users/runner/work/CarketaV2/CarketaV2/ios/***.keychain-db
	/Users/runner/work/CarketaV2/CarketaV2/ios/***
	/Users/runner/work/CarketaV2/CarketaV2/ios/***.keychain
```

fastlane version 2.0.0 action. xcod _14.2.
