### DISCUSSION TITLE
Import_certificate and sigh scenario: No matching provisioning profile found and can not create a new one because you enabled `readonly`

### DISCUSSION THREAD

**Discussion by kdjomeda** [fastlane/fastlane#21163] [Q&A]
I have picked up a project mid way and trying to automate the releases. It's a react-native project android/iOS. 

There are a number of profile and certificate already created so I am `NOT using fastlane MATCH` feature just yet  since this type of error is tied to the match usage from my readings, it would mean I would have to remove all existing certificates and profile on the apple developer account. 

So I created a new certificate and a provisioning that I am downloading into a keychain that we create. But for some reason, The installed certificate doesn't seem to match the downloaded provisioning file pulled by `sigh`. The sigh command's certificate verification throws : "No matching provisioning profile found and can not create a new one because you enabled `readonly`". Below are the output our GitHub actions and the Fastline that I am using.

```
bundle exec fastlane ios build_and_pushto_firebase
3
  shell: /bin/bash -e {0}
4
  env:
5
    PATH: /usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Library/Frameworks/Python.framework/Versions/Current/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.9.3/x64
6
    ASC_KEY_ID: ***
7
    ASC_ISSUER_ID: ***
8
    ASC_KEY: ***
9
    KEYCHAIN_NAME: dev_keychain
10
    KEYCHAIN_PASSWORD: mMUZB1d4Uc8Uxg94cos6VLcdk
11
    SIGNING_CERTIFICATE_PATH: ./certificates/dev_certificate.p12
12
    SIGNING_CERTIFATE_PASSPHRASE: ***
13
    GITHUB_ACTION_RUN_NUMBER: 10
14
    IOS_PROFILE_NAME: DEV_GitHub_Actions_Profile
15
    IOS_OUTPUT_NAME: dev-is
16
    IOS_TEAM_ID: 
17
    FIREBASE_CLI_TOKEN: ***
18
    FIREBASE_APP_ID: ***
19
    FIREBASE_DIST_GROUP: dev-ios-group
20
+-------------------------------------------+---------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
21
|                                                                                                                                                                                                                 Used plugins                                                                                                                                                                                                                 |
22
+-------------------------------------------+---------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
23
| Plugin                                    | Version | Action                                                                                                                                                                                                                                                                                                                                                                                 |
24
+-------------------------------------------+---------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
25
| fastlane-plugin-versioning                | 0.5.1   | ci_build_number, get_app_store_version_number, get_build_number_from_plist, get_build_number_from_xcodeproj, get_info_plist_path, get_version_number_from_git_branch, get_version_number_from_plist, get_version_number_from_xcodeproj, increment_build_number_in_plist, increment_build_number_in_xcodeproj, increment_version_number_in_plist, increment_version_number_in_xcodeproj |
26
| fastlane-plugin-firebase_app_distribution | 0.5.0   | firebase_app_distribution, firebase_app_distribution_add_testers, firebase_app_distribution_get_latest_release, firebase_app_distribution_get_udids, firebase_app_distribution_remove_testers                                                                                                                                                                                          |
27
+-------------------------------------------+---------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
28

29
[13:23:22]: ------------------------------
30
[13:23:22]: --- Step: default_platform ---
31
[13:23:22]: ------------------------------
32
[13:23:22]: Driving the lane 'ios build_and_pushto_firebase' 🚀
33
[13:23:22]: -------------------------------------------------
34
[13:23:22]: --- Step: Switch to ios load_asc_api_key lane ---
35
[13:23:22]: -------------------------------------------------
36
[13:23:22]: Cruising over to lane 'ios load_asc_api_key' 🚖
37
[13:23:22]: ---------------------------------------
38
[13:23:22]: --- Step: app_store_connect_api_key ---
39
[13:23:22]: ---------------------------------------
40
[13:23:22]: Cruising back to lane 'ios build_and_pushto_firebase' 🚘
41
[13:23:22]: -------------------------------------------------------
42
[13:23:22]: --- Step: Switch to ios prepare_manual_signing lane ---
43
[13:23:22]: -------------------------------------------------------
44
[13:23:22]: Cruising over to lane 'ios prepare_manual_signing' 🚖
45
[13:23:22]: -----------------------------
46
[13:23:22]: --- Step: create_keychain ---
47
[13:23:22]: -----------------------------
48
[13:23:22]: $ security list-keychains -d user
49
[13:23:22]: ▸ "/Users/runner/Library/Keychains/dev_keychain-db"
50
[13:23:22]: Found keychain '/Users/runner/Library/Keychains/dev_keychain-db' in list-keychains, adding to search list skipped
51
[13:23:22]: --------------------------------
52
[13:23:22]: --- Step: import_certificate ---
53
[13:23:22]: --------------------------------
54
[13:23:22]: $ security import ./certificates/dev_certificate.p12 -k '/Users/runner/Library/Keychains/dev_keychain-db' -P ******** -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild -T /usr/bin/productsign
55
[13:23:23]: ▸ 1 identity imported.
56
[13:23:23]: Setting key partition list... (this can take a minute if there are a lot of keys installed)
57
[13:23:23]: $ security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k ******** /Users/runner/Library/Keychains/dev_keychain-db 1> /dev/null
58
[13:23:23]: ------------------
59
[13:23:23]: --- Step: sigh ---
60
[13:23:23]: ------------------
61

62
+-------------------------------------+----------------------------+
63
|                     Summary for sigh 2.212.1                     |
64
+-------------------------------------+----------------------------+
65
| adhoc                               | false                      |
66
| provisioning_name                   | DEV_GitHub_Actions_Profile |
67
| api_key                             | ********                   |
68
| skip_certificate_verification       | false                      |
69
| readonly                            | true                       |
70
| developer_id                        | false                      |
71
| development                         | false                      |
72
| skip_install                        | false                      |
73
| force                               | false                      |
74
| include_mac_in_profiles             | false                      |
75
| app_identifier                      | com.code.app         |
76
| ignore_profiles_with_different_name | false                      |
77
| skip_fetch_profiles                 | false                      |
78
| include_all_certificates            | false                      |
79
| platform                            | ios                        |
80
| fail_on_name_taken                  | false                      |
81
+-------------------------------------+----------------------------+
82

83
[13:23:23]: Creating authorization token for App Store Connect API
84
[13:23:23]: Fetching profiles...
85
[13:23:23]: Verifying certificates...
86
+---------------------------+-----------------------------------------------------+
87
|                                  Lane Context                                   |
88
+---------------------------+-----------------------------------------------------+
89
| DEFAULT_PLATFORM          | ios                                                 |
90
| PLATFORM_NAME             | ios                                                 |
91
| LANE_NAME                 | ios build_and_pushto_firebase                       |
92
| KEYCHAIN_PATH             | ~/Library/Keychains/dev_keychain               |
93
| ORIGINAL_DEFAULT_KEYCHAIN | "/Users/runner/Library/Keychains/login.keychain-db" |
94
+---------------------------+-----------------------------------------------------+
95

96
[13:23:23]: No matching provisioning profile found and can not create a new one because you enabled `readonly`
97
[!] No matching provisioning profile found and can not create a new one because you enabled `readonly`
98

99
+------+-------------------------------------------+-------------+
100
|                        fastlane summary                        |
101
+------+-------------------------------------------+-------------+
102
| Step | Action                                    | Time (in s) |
103
+------+-------------------------------------------+-------------+
104
| 1    | default_platform                          | 0           |
105
| 2    | Switch to ios load_asc_api_key lane       | 0           |
106
| 3    | app_store_connect_api_key                 | 0           |
107
| 4    | Switch to ios prepare_manual_signing lane | 0           |
108
| 5    | create_keychain                           | 0           |
109
| 6    | import_certificate                        | 0           |
110
| 💥   | sigh                                      | 0           |
111
+------+-------------------------------------------+-------------+
112

113
[13:23:23]: fastlane finished with errors
114
Error: Process completed with exit code 1.
```

Below is how the Fastfile looks like 

```
default_platform(:ios)

# platform :ios do
#   desc "Description of what the lane does"
#   lane :custom_lane do
#     # add actions here: https://docs.fastlane.tools/actions
#   end
# end


platform :ios do
  desc "This is the dev release for ios"

  lane :load_asc_api_key do
    app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_KEY'],
      is_key_content_base64: false,
      in_house: false
    )
  end

  lane :prepare_manual_signing do |options|
    team_id = ENV['IOS_TEAM_ID']
    api_key = lane_context[SharedValues::APP_STORE_CONNECT_API_KEY]

    keychain_name = ENV['KEYCHAIN_NAME']
    keychain_password = ENV['KEYCHAIN_PASSWORD']

    # deleting any existing keychain if any
    delete_keychain(
      name: keychain_name
    )if File.exist? File.expand_path("~/Library/Keychains/#{keychain_name}-db")

    #creating a new keychain to use and import certificate into
    create_keychain(
      name: keychain_name,
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 360
    )

    # importing our p12 certificate into the just created keychain
    import_certificate(
      certificate_path: ENV['SIGNING_CERTIFICATE_PATH'],
      certificate_password: ENV['SIGNING_CERTIFATE_PASSPHRASE'],
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      log_output: true
      )

      # Importing provisioning files from app store connect
      sigh(
        adhoc: options[:adhoc],
        provisioning_name: ENV['IOS_PROFILE_NAME'],
        api_key: api_key,
        skip_certificate_verification: false,
        readonly: 
      )
  end



  lane :alpha_release do
  # increment_version_number_in_plist(xcodeproj: './Hero.xcodeproj',bump_type: 'patch')
    app_identifier = CredentialsManager::AppConfig.try_fetch_value(:app_identifier)
    increment_build_number_in_pllist(
      build_number: ENV['GITHUB_ACTION_RUN_NUMBER']
    )
    profile_name = ENV['IOS_PROFILE_NAME']
    output_name = ENV['IOS_OUTPUT_NAME']
    export_method = "adhoc"

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "./XXX.xcodeproj",
      code_sign_identity: "iPhone Distribution",
      team_id: ENV['IOS_TEAM_ID'],
      bundle_identifier: app_identifier,
      profile_name: profile_name
    )

    gym(
      scheme: "Hero",
      output_name: output_name,
      configuration: "Release",
      export_options: {
        method: export_method,
        provisioningProfiles: {
          app_identifier => profile_name
        }
      }
    )

    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID'],
      firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
      groups: ENV['FIREBASE_DIST_GROUP'],
      release_notes: "Git commit: #{last_git_commit[:abbreviated_commit_hash]}",
  )

  end

  lane :build_and_pushto_firebase do
    load_asc_api_key
    prepare_manual_signing
    # alpha_release
  end

end

```

Here is also my GitHub actions

```
name: iOS developer build

on: 
  push:
    branches:
      - feat/fastlane-ios
      # - develop*
      # - feat/*

jobs:
  android-build:
    name: iOS Build
    runs-on: macos-latest
    # environment: dev
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          yarn install
          
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'
          bundler-cache: true

      - name: Checking Ruby Component versions
        working-directory: ./ios
        run: |
          gem install bundler && bundle install
          # gem install fastlane
      
      # Install the Firebase app distribution plugin with fastlane
      - name: Install fastlane other plugins
        working-directory: ./ios      
        run: |
          bundle exec fastlane add_plugin firebase_app_distribution
          bundle exec fastlane add_plugin versioning

      - name: Recreate ios p12 out of base64 string using unix native tools
        working-directory: ./ios
        env:
          P12_CERTIFICATE_BASE64:  ${{ secrets.DEV_IOS_P12_CERTIFICATE_BASE64_FILE }}
          DECODED_CERTIFICATE_PATH: ${{ vars.DEV_IOS_P12_CERT_FOLDER_PATH }}
          DECODED_CERTIFICATE_FILE: ${{ vars.DEV_IOS_P12_CERT_NAME }}
        run: |
          mkdir $DECODED_CERTIFICATE_PATH
          echo -n "$P12_CERTIFICATE_BASE64" | base64 --decode > $DECODED_CERTIFICATE_PATH/$DECODED_CERTIFICATE_FILE


      - name: Build and distribute to firebase
        working-directory: ./ios      
        run: bundle exec fastlane ios build_and_pushto_firebase
        env:
          ASC_KEY_ID: ${{ secrets.IOS_ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.IOS_ASC_ISSUER_ID }}
          ASC_KEY: ${{ secrets.IOS_ASC_P8_KEY_FILE }}
          KEYCHAIN_NAME: ${{ vars.DEV_IOS_ACTION_KEYCHAIN_NAME }}
          KEYCHAIN_PASSWORD: ${{ vars.DEV_IOS_ACTION_KEYCHAIN_PASSWORD }}
          SIGNING_CERTIFICATE_PATH: ${{ vars.DEV_IOS_P12_CERT_FOLDER_PATH }}/${{ vars.DEV_IOS_P12_CERT_NAME }}
          SIGNING_CERTIFATE_PASSPHRASE: ${{ secrets.DEV_IOS_P12_CERTIFICATE_PASSPHRASE }}
          GITHUB_ACTION_RUN_NUMBER: ${{ github.run_number }}
          IOS_PROFILE_NAME: ${{ vars.DEV_IOS_PROFILE_NAME }}
          IOS_OUTPUT_NAME: ${{ vars.DEV_IOS_OUTPUT_NAME }}
          IOS_TEAM_ID: ${{ secrets.IOS_TEAM_ID }}
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.DEV_IOS_FIREBASE_APP_ID }}
          FIREBASE_DIST_GROUP: "naya-dev-ios"
      
      - name: Certificate keychain Troubleshooting
        working-directory: ./ios 
        run: |
          security list-keychains
          security find-identity
          security find-key
          security find-identity /Users/runner/Library/Keychains/dev_keychain-db
          security find-certificate -c "iPhone Distribution: Exxxs xx (xxxxxxx)" -p ~/Library/Keychains/dev_keychain-db | openssl x509 -text -noout


      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios-build ipa
          path: "${{ github.workspace }}/${{ vars.DEV_IOS_OUTPUT_NAME }}.ipa"

```

Is there anything I am doing wrong ? Kindly let me know if I am making a mistake and how to get out of this situation. Thanks in advance
