### DISCUSSION TITLE
Builds uploaded to testflight won't get past the LaunchScreen

### DISCUSSION THREAD

**Discussion by juandozuna** [fastlane/fastlane#21267] [General]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I created a release workflow within fastlane for our Flutter app into Testflight on AppStoreConnect. It works well when the lane is ran locally on my machine and I'm able to install the resulting IPA on my phone from the Testflight app without any errors. 

When I execute the same process on a github action, everything runs smoothly, but when installing from Testflight and opening the app, it appears to be frozen on the LaunchScreen. 

Here's my github action
```
  ios-dev-deploy:
    name: 'iOS Development Deploy'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Get Flutter version from FVM
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: '14.2'

      - name: Bundle install
        run: cd ios && bundle install

      - name: Fastlane Process
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'release_dev'
          subdirectory: 'ios'
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GIT_PASS: ${{ secrets.GIT_PASS }}
          GIT_USER: ${{ secrets.GIT_USER }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
          APPLE_KEY_CONTENT: ${{ secrets.APPLE_KEY_CONTENT }}
```

And here's the code of the used lanes from my Fastfile
```rb
platform :ios do
    flavor = nil
    user = ENV["FASTLANE_USER"]
    app_identifier = ""
    team_name= ""
    team_id = ""
    git_user = ENV["GIT_USER"]
    git_pass = ENV["GIT_PASS"]
    team_itc_id = ""
    scheme = nil

    lane :set_env_variables do
            setup_ci

            ENV["FASTLANE_TEAM_NAME"] = team_name
            ENV["FASTLANE_ITC_TEAM_NAME"] = team_name
            ENV["APP_IDENTIFIER"] = app_identifier
            ENV["TEAM_ID"] = team_id
            ENV["FASTLANE_TEAM_ID"] = team_id
            ENV["TEAM_ITC_ID"] = team_itc_id
            ENV["MATCH_APP_IDENTIFIER"] = app_identifier
            ENV["MATCH_GIT_URL"] = "https://github.com/NerdUnited-Galvan/galvan_app_match.git"
            ENV["MATCH_TYPE"] = "appstore"
#             ENV["MATCH_KEYCHAIN_PASSWORD"] = ENV["MATCH_PASSWORD"]
            if !is_ci
                ENV["MATCH_USERNAME"] = ENV["FASTLANE_USER"]
            end
            ENV["PILOT_APP_IDENTIFIER"] = app_identifier
            ENV["PILOT_TEAM_ID"]= team_id
            ENV["PILOT_TEAM_NAME"]=team_name
            ENV["PILOT_IPA"] = "./build/Runner.ipa"
            ENV["PILOT_SKIP_WAITING_FOR_BUILD_PROCESSING"] = "true"
            ENV["PILOT_SKIP_SUBMISSION"] = "true"
            ENV["FL_PROJECT_SIGNING_PROJECT_PATH"] = "Runner.xcodeproj"
            ENV["FL_PROJECT_SIGNING_TARGET"] = "Runner"
            ENV["FL_PROJECT_SIGNING_BUILD_CONFIGURATIONS"] = "Release"
            ENV["FL_PROJECT_USE_AUTOMATIC_SIGNING"] = "false"
            ENV["FL_CODE_SIGNING_IDENTITY"] = "iPhone Distribution"
    end

desc "Sync Signing"
  lane :signing do
    sync_code_signing(
    readonly: is_ci,
    type: "appstore",
        git_basic_authorization: Base64.strict_encode64("#{git_user}:#{git_pass}"),
        api_key: app_store_connect_api_key(
                       key_id: ENV["APPLE_ID"],
                       issuer_id: ENV["APPLE_ISSUER_ID"],
                       key_content: ENV["APPLE_KEY_CONTENT"]
                     )
    )
  end

  desc "Build Binary"
  lane :build do
    signing

        puts "Fastlane Building Flutter App"
        Dir.chdir "../.." do
            sh("flutter", "clean")
            sh("flutter", "pub", "get")
            sh("flutter", "build", "ios", "--flavor", flavor, "-t", "lib/main_#{flavor}.dart")
        end

    mapping = Actions.lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]

    build_ios_app(
        workspace: "Runner.xcworkspace",
        silent: true,
        scheme: scheme,
        configuration: "Release-#{scheme}",
        export_method: "app-store",
        output_directory: "./build",
    )
  end

  desc "Release to Appstore"
  lane :release do

    build
    upload_to_testflight(
      api_key: apikey,
      ipa: './build/Runner.ipa',
      app_identifier: app_identifier,
    )

  end

    lane :build_dev do
        flavor = "dev"
        scheme = "dev"
        app_identifier = "com.appname.dev"

        set_env_variables

        build
    end

    lane :release_dev do
        build_dev
        upload_to_testflight
    end
```

##### Command executed
`fastlane release_dev`

##### Complete output when running fastlane, including the stack trace and command used
![image](https://github.com/fastlane/fastlane/assets/29807530/3ba7820d-5403-41f1-be67-814a4f74b761)

### Environment
swift-driver version: 1.62.15 DEBUG [2023-05-11 11:49:46.52]: Checking if there are any plugins that should be loaded...
