### DISCUSSION TITLE
How to use Fastlane match with a repository in Azure Devops in the CI/CD?

### DISCUSSION THREAD

**Discussion by jpstijn** [fastlane/fastlane#21606] [Q&A]
I have tried to use Fastlane match with a repository in Azure Devops but I cannot make it work. Match cannot access the repository.

I have tried the following:

File: build-ios.yml (Azure pipeline yml)
$(match_git_bearer_authorization) = A pat token from my own azure account.
```yml
 - task: CmdLine@2
   name: ${{ parameters.deployMethod }}_IOS
   env:
      MATCH_GIT_BEARER_AUTHORIZATION: $(match_git_bearer_authorization)
      AZURE_TOKEN:  $(match_git_bearer_authorization)
```

File: build-ios.yml (Azure pipeline yml)
```yml
 - task: CmdLine@2
   name: ${{ parameters.deployMethod }}_IOS
   env:
      MATCH_GIT_BEARER_AUTHORIZATION: $(System.Accestoken)
      AZURE_TOKEN:  $(System.Accestoken)
```

File: Fastfile
```Ruby
    match(
      api_key: api_key,
      type: options[:type],
      git_url:  "https://company.visualstudio.com/Project/_git/App.ReactNative.CodeSigning",
      git_bearer_authorization: ENV['MATCH_GIT_BEARER_AUTHORIZATION'],
    )
```

File: Fastfile
```Ruby
    match(
      api_key: api_key,
      type: options[:type],
      git_url:  "https://#{ENV['AZURE_TOKEN']}@dev.azure.com/company/Project/_git/App.ReactNative.CodeSigning".
      git_bearer_authorization: Base64.strict_encode64("company:#{ENV['AZURE_TOKEN']}")
    )
```

Also added the following configuration in Azure Devops:
<img width="1028" alt="image" src="https://github.com/fastlane/fastlane/assets/24881734/5862a17c-71ca-4886-b067-edf258863a0b">

But I keep getting: 

```
ERROR [2023-10-31 20:47:26.55]: Exit status: 128
ERROR [2023-10-31 20:47:26.55]: Error cloning certificates repo, please make sure you have read access to the repository you want to use
```

Using a script in the pipeline like this works: 
```yml
inputs:
              script: |
                git clone "https://company.visualstudio.com/Project/_git/App.ReactNative.CodeSigning" -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)"
                ls -la
```

**Comment by mikokau** [comment]
Hey, I came across this same problem with Azure Pipelines and Fastlane match access.

On my pipeline this was fixed by adding certificates repository as a resource and a checkout step for the certs repo.

I'm also using MATCH_GIT_BEARER_AUTHORIZATION env variable.

On first run this will ask permission to use the other repository as resource which you will have to permit.

```
resources:
  repositories:
    - repository: ios-certs
      name: ios-certs
      type: git
```


```
jobs:
    - job: Deploy
      workspace:
        clean: all
      
      steps:
      - checkout: self
      - checkout: ios-certs
```

```
- script: bundle exec fastlane ios deploy_ios
        displayName: 'Deploy iOS'
        env:
          MATCH_GIT_BEARER_AUTHORIZATION: $(System.AccessToken)
```
