### DISCUSSION TITLE
Fastlane usage for github CI/CD workflow to build ios apps

### DISCUSSION THREAD

**Discussion by fajarAliM** [fastlane/fastlane#22143] [Q&A]
Hello community,

I am trying to implement an iOS build automatically in CI/CD workflow using Github action with Fastlane. The project is in ionic and capacitor and it should build debug .ipa file to upload somewhere.
I am also using fastlane match.

But the github action fails with error: 
"Signing for "App" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'App' from project 'App')"

The below is .yml action file which works for that workflow.

```
build-ios:
    # needs: build-android
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install Dependencies
      working-directory: BucketIO.Ionic
      run: npm cache clean --force && npm install
    - name: Install Ionic cli globally
      working-directory: BucketIO.Ionic
      run: npm install -g @ionic/cli
    - name: Set up Ruby for Fastlane
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.0' # Specify the Ruby version Fastlane will run on
    - name: Install Fastlane
      run: gem install fastlane
    - name: Install Provisioning Profile using Match
      working-directory: BucketIO.Ionic
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
      run: |
        fastlane match development --app_identifier "com.myapp.app" --readonly
    - name: Build BucketIO for iOS
      working-directory: BucketIO.Ionic
      run: |
        ionic build
        npx cap add ios
        npx cap copy ios
        npx cap sync ios
        fastlane ios ios_build
      env:
        MATCH_APP_IDENTIFIER: com.bucketIO.app
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    - name: Upload IPA to Sauce Labs
      working-directory: BucketIO.Ionic
      run: 'curl -u "${{ secrets.SAUCE_USERNAME }}:${{ secrets.SAUCE_ACCESS_KEY }}" -X POST -H "Content-Type: application/octet-stream" --data-binary @./ios/App/build/App.ipa "https://api.us-west-1.saucelabs.com/v1/storage/upload"'
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
```

And there is my Fastfile configuration below:

```
default_platform(:ios)

platform :ios do
  ios_dir = File.expand_path('../ios')

  desc "Sync provisioning profiles using Match"
  lane :sync_profiles do
    match(type: "development", app_identifier: "com.myapp.app", readonly: true)
  end

  desc "Build ios .ipa file for development"
  lane :ios_build do
    match(type: "development", readonly: true)
    build_app(
      workspace: "./ios/App/App.xcworkspace",
      scheme: "App",
      export_method: "development",
      output_directory: "./ios/App/build",
      output_name: "App.ipa",
      export_team_id: "development_team_id"
    )
  end
end
```

I am new to fastlane and tried many ways to resolve this issue, but couldn't find the solution for it so far.
How can I load development team while ios build with those configurations. I am in very urgent with this issue.
