### ISSUE TITLE
adb_spec fails when `ANDROID_SDK_ROOT` is set on local machine to something else

### ISSUE THREAD

**Issue by joshdholtz** [fastlane/fastlane#12300]
- Might need to also check other Android environment variables besides `ANDROID_SDK_ROOT` 😊 

```
Failures:

  1) Fastlane Fastlane::FastFile adb picks up path from ANDROID_SDK_ROOT environment variable
     Failure/Error: expect(result).to eq(" /usr/local/android-sdk/platform-tools/adb test")

       expected: " /usr/local/android-sdk/platform-tools/adb test"
            got: " /Users/josh/Library/Android/sdk/platform-tools/adb test"

       (compared using ==)
     # ./fastlane/spec/actions_specs/adb_spec.rb:18:in `block (4 levels) in <top (required)>'
```
