### ISSUE TITLE
"DEPRECATION WARNING: Faraday::Error::ConnectionFailed is deprecated! Use Faraday::ConnectionFailed instead." / Fastlane spaceauth: Could not login to App Store Connect

### ISSUE THREAD

**Issue by gbhrdt** [fastlane/fastlane#15397]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
A weird error appears when trying to login via spaceauth.
I am not able to reproduce this locally. The error occurs on our servers.
I also tried another server with a fresh IP, this did not resolve the problem.

##### Command executed
`fastlane spaceauth`

##### Complete output when running fastlane, including the stack trace and command used
	# fastlane spaceauth
	[✔] 🚀
	[23:39:03]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
	Username: xxx@xxx.xxx
	Logging into to App Store Connect (xxx@xxx.xxx)...
	-------------------------------------------------------------------------------------
	Please provide your Apple Developer Program account credentials
	You can also pass the password using the `FASTLANE_PASSWORD` environment variable
	-------------------------------------------------------------------------------------
	Password (for xxx@xxx.xxx): ***
	Two-factor Authentication (6 digits code) is enabled for account 'xxx@xxx.xxx'
	More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

	If you're running this in a non-interactive session (e.g. server or CI)
	check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

	(Input `sms` to escape this prompt and select a trusted phone number to send the code as a text message)

	(You can also set the environment variable `SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER` to automate this)
	(Read more at: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/Authentication.md#auto-select-sms-via-spaceship-2fa-sms-default-phone-number)

	Please enter the 6 digit code:
	xxxxxx
	Requesting session...
	DEPRECATION WARNING: Faraday::Error::ConnectionFailed is deprecated! Use Faraday::ConnectionFailed instead.
	DEPRECATION WARNING: Faraday::Error::TimeoutError is deprecated! Use Faraday::TimeoutError instead.
	Could not login to App Store Connect
	Please check your credentials and try again.
	This could be an issue with App Store Connect,
	Please try unsetting the FASTLANE_SESSION environment variable
	(if it is set) and re-run `fastlane spaceauth`

	Exception type: RuntimeError

	Looking for related GitHub issues on fastlane/fastlane...

	➡️  "Can't modify frozen String" error when setting output_name in Gymfile via ENV[...]
	    https://github.com/fastlane/fastlane/issues/8548 [closed] 6 💬
	    18 Jun 2017

	➡️  Exception running gym with ouput_name set to ENV variable
	    https://github.com/fastlane/fastlane/issues/5206 [closed] 7 💬
	    06 Dec 2016

	➡️  Getting Exception on Wildcard App Identifier
	    https://github.com/fastlane/fastlane/issues/3063 [closed] 3 💬
	    22 Sep 2016

	and 1 more at: https://github.com/fastlane/fastlane/search?q=can%27t%20modify%20frozen%20String&type=Issues&utf8=✓

	/var/lib/gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:811:in `force_encoding': [!] can't modify frozen String (RuntimeError)
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:811:in `log_response'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:846:in `block in send_request'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:620:in `with_retry'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:844:in `send_request'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:688:in `request'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:290:in `store_session'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:189:in `handle_two_factor'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:20:in `handle_two_step_or_factor'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:494:in `send_shared_login_request'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:770:in `do_login'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:384:in `login'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/client.rb:346:in `login'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/spaceauth_runner.rb:18:in `run'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/commands_generator.rb:43:in `block (2 levels) in run'
		from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
		from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
		from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
		from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/commands_generator.rb:49:in `run'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/spaceship/lib/spaceship/commands_generator.rb:14:in `start'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
		from /var/lib/gems/2.3.0/gems/fastlane-2.131.0/bin/fastlane:23:in `<top (required)>'
		from /usr/local/bin/fastlane:22:in `load'
		from /usr/local/bin/fastlane:22:in `<main>'

**Comment by nareen2** [comment]
Seeing the same issue

**Comment by yenda** [comment]
I solved it by downgrading faraday to the previous version (before 0.16)

**Comment by janpio** [comment]
Can you share how exactly you did that @yenda so others can just follow your instructions?

**Comment by yenda** [comment]
@janpio your PR will fix it in next release I suppose but for now:

add `gem "faraday", "0.15.4"' in your 'Gemfile"
run `bundle install`

**Comment by paulpopiel** [comment]
Likewise faced the same issue, also solved by downgrading faraday. 
Thanks @yenda

**Comment by Panajev** [comment]
Faraday 0.16.2 has been pushed to ruby gems, does it solve this issue?

**Comment by janpio** [comment]
We will know when CI finished testing https://github.com/fastlane/fastlane/pull/15407

**Comment by janpio** [comment]
Unfortunately not, still getting test failures like this:

```
Failures:
  1) Spaceship::Portal::Persons should change role
     Failure/Error: expect { person.change_role("member") }.to_not(raise_error)
       expected no Exception, got #<RuntimeError: can't modify frozen String> with backtrace:
         # ./spaceship/lib/spaceship/client.rb:811:in `force_encoding'
         # ./spaceship/lib/spaceship/client.rb:811:in `log_response'
         # ./spaceship/lib/spaceship/client.rb:846:in `block in send_request'
         # ./spaceship/lib/spaceship/client.rb:620:in `with_retry'
         # ./spaceship/lib/spaceship/client.rb:844:in `send_request'
         # ./spaceship/lib/spaceship/client.rb:688:in `request'
         # ./spaceship/lib/spaceship/portal/portal_client.rb:449:in `team_set_role'
         # ./spaceship/lib/spaceship/portal/person.rb:45:in `change_role'
         # ./spaceship/spec/portal/person_spec.rb:58:in `block (3 levels) in <top (required)>'
         # ./spaceship/spec/portal/person_spec.rb:58:in `block (2 levels) in <top (required)>'
     # ./spaceship/spec/portal/person_spec.rb:58:in `block (2 levels) in <top (required)>'
  2) Spaceship::Tunes::IAPList IAPList can delete
     Failure/Error: deleted = app.in_app_purchases.find("go.find.me").delete!
     RuntimeError:
       can't modify frozen String
     # ./spaceship/lib/spaceship/client.rb:811:in `force_encoding'
     # ./spaceship/lib/spaceship/client.rb:811:in `log_response'
     # ./spaceship/lib/spaceship/client.rb:846:in `block in send_request'
     # ./spaceship/lib/spaceship/client.rb:620:in `with_retry'
     # ./spaceship/lib/spaceship/client.rb:844:in `send_request'
     # ./spaceship/lib/spaceship/client.rb:688:in `request'
     # ./spaceship/lib/spaceship/tunes/tunes_client.rb:1235:in `delete_iap!'
     # ./spaceship/lib/spaceship/tunes/iap_list.rb:72:in `delete!'
     # ./spaceship/spec/tunes/iap_list_spec.rb:28:in `block (3 levels) in <top (required)>'
  3) Spaceship::Tunes::Members members creates a new member role: admin, apps: all
     Failure/Error: Spaceship::Members.create!(firstname: "Helmut", lastname: "Januschka", email_address: "helmut@januschka.com")
     RuntimeError:
       can't modify frozen String
     # ./spaceship/lib/spaceship/client.rb:811:in `force_encoding'
     # ./spaceship/lib/spaceship/client.rb:811:in `log_response'
     # ./spaceship/lib/spaceship/client.rb:846:in `block in send_request'
     # ./spaceship/lib/spaceship/client.rb:620:in `with_retry'
     # ./spaceship/lib/spaceship/client.rb:844:in `send_request'
     # ./spaceship/lib/spaceship/client.rb:688:in `request'
     # ./spaceship/lib/spaceship/tunes/tunes_client.rb:502:in `create_member!'
     # ./spaceship/lib/spaceship/tunes/members.rb:26:in `create!'
     # ./spaceship/spec/tunes/members_spec.rb:19:in `block (4 levels) in <top (required)>'
```

Reported at faraday: https://github.com/lostisland/faraday/issues/1038
