### ISSUE TITLE
VSTS Fastlane SnapShot - test_without_building, not able to pass derivedDataPath

### ISSUE THREAD

**Issue by JulesMoorhouse** [fastlane/fastlane#15486]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Tool: Snapshot

Is this a question about documentation? Perhaps, although it doesn't go into that much detail.

 Is this a question about a third party plugin? (If so, please go to the plugin repository first)  No

#### Question Description

When running fast lane snapshot in VSTS CI, my test takes longer than an hour, so it fails, therefore I need to build first and use the 'test_without_building' option and therefore need to pass a 'derived_data_path'. 

However I can't pass this value into fastfile or as a command line argument

Here's my build task..

```
pool:
  vmImage: 'macOS-10.14'

variables:
  scheme: 'myapp'
  sdk: 'iphoneos'
  configuration: 'Debug'
  FASTLANE_DISABLE_COLORS: 1

steps:
- script: |
    git config --global credential.helper store
    git clone https://$(gitUser):$(gitPat)@myrepo.visualstudio.com/Pods/_git/my-specs
  workingDirectory: $(Agent.BuildDirectory)
  displayName: 'Git clone'

- task: CocoaPods@0
  inputs:
    forceRepoUpdate: false
    projectDirectory: '$(system.defaultWorkingDirectory)'
  displayName: 'pod install using the CocoaPods task with a not forced repo update and a custom project directory'

- task: Xcode@5
  displayName: 'Xcode debug build'
  inputs:
    actions: 'build'
    scheme: '$(scheme)'
    sdk: '$(sdk)'
    configuration: '$(configuration)'
    xcodeVersion: 'specifyPath'
    xcodeDeveloperDir: '/Applications/Xcode_11.1.app/Contents/Developer'
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: false
    xcWorkspacePath: 'myapp.xcworkspace'
    useXcpretty: true

- script: |
    CALL gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: sudo gem install fastlane -NV
  displayName: 'Install Fastlane'

- script: |
    bundle install
    fastlane snapshot reset_simulators --ios 9.3,10.0,11.0.1,12.2,13.1 --force
  displayName: 'fastlane reset_simulators'

- script: |
    bundle install
   # fastlane screenshots --derived_data_path '$(agent.buildDirectory)/output/$(sdk)/$(configuration)' # doesn't work

    fastlane screenshots --xcargs '\-derivedDataPath "$(agent.buildDirectory)/output/$(sdk)/$(configuration)"' # doesn't work
  displayName: 'fastlane screenshots'
```

Here's my fast file
```
  before_all do
  end

  lane :screenshots do
    snapshot(
      devices: [
      "iPhone 4s",
      "iPhone 5",
      "iPhone X",
      "iPhone Xʀ",
      "iPhone Xs",
      "iPhone Xs Max",
      "iPhone 6 Plus",
      "iPhone 6",
      "iPad Air 2",
      "iPad Pro (12.9-inch)",
      "iPad Pro (11-inch)",
      "iPad Pro (10.5-inch)",
      #"iPad (7th generation)", # need to put back in
      "iPad Pro (9.7-inch)"
      ],
      languages: [
        "de-DE"
      ], 
      output_directory: "../screenshots/myapp",
      scheme: "myapp", # <---- Use the "regular" scheme name, not UI tests
      workspace: "./myapp.xcworkspace",
      launch_arguments: ["-isUITest multi"],
      stop_after_first_error: false,
      output_simulator_logs: true,
      clear_previous_screenshots: true,
      #concurrent_simulators: false
      concurrent_simulators: true,
      test_without_building: true, # need to remove when no using ci
      derived_data_path: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)' # doesn't work
    )

  end
```

I can't seem to use an vsts environmental variable in my fastfile or pass in a command line argument. Also I can't see a fastlane environmental variable I could use.

I'm using snapshot as I want to run the test on multiple devices and ideally once I get it working get access to the screenshots. I use snapshot to highlight any autolayout issues as well as for screenshots.
