### ISSUE TITLE
"You must use Bundler 2 or greater with this lockfile" error in CircleCI

### ISSUE THREAD

**Issue by zerinasever** [fastlane/fastlane#15689]
Hi,

I have problem when I updated bundler version from 1.16.3 to 2.0.2. I got error on CI:
"You must use Bundler 2 or greater with this lockfile"

I changed fastlane version from 2.17.1 to 2.136.0 and I successfully updated bundler version, new Gemfile.lock file is created with:
BUNDLED WITH
   2.0.2
Output of command bundler -v is:
Bundler version 2.0.2

Output of fastlane -env is:
### Stack

| Key                         | Value                                                         |
| --------------------------- | ------------------------------------------------------------- |
| OS                          | debian_based buster/sid                                       |
| Ruby                        | 2.5.1                                                         |
| Bundler?                    | false                                                         |
| Git                         | git version 2.17.1                                            |
| Installation Source         | /usr/local/bin/fastlane                                       |
| Host                        | Ubuntu 18.04.2 LTS debian_based buster/sid (5.0.0-36-generic) |
| Ruby Lib Dir                | /usr/lib                                                      |
| OpenSSL Version             | OpenSSL 1.1.1  11 Sep 2018                                    |
| Is contained                | false                                                         |
| Is homebrew                 | false                                                         |
| Is installed via Fabric.app | false                                                         |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.136.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.13.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.68.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2019.1009  |
| mime-types                | 3.3          |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.1       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| CFPropertyList            | 3.0.1        |
| claide                    | 1.0.3        |
| addressable               | 2.7.0        |
| babosa                    | 1.0.3        |
| json                      | 2.2.0        |
| ipaddr                    | 1.2.0        |
| openssl                   | 2.1.1        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2019-11-21**

I do not understand what may be a problem, so I will appreciate if you can help.

**Comment by janpio** [comment]
Can you please share the complete output you are getting with the error message?

**Comment by zerinasever** [comment]
I just get next:
![Screenshot from 2019-11-21 10-11-34](https://user-images.githubusercontent.com/45461463/69340261-5bd3e680-0c67-11ea-8749-bebc8a0428db.png)

**Comment by janpio** [comment]
Can you share your Circle CI config? The "Install Ruby Dependencies" might use a different bundler version - so best check in that step which version is being used.

**Comment by zerinasever** [comment]
Yes, of course, everything what can be helpful to resolve that problem:
`
version: 2

android_dependencies: &android_dependencies
  run:
    name: Install Android Dependencies
    command: ./gradlew androidDependencies

ruby_dependencies: &ruby_dependencies
  run:
    name: Install Ruby Dependencies
    command: bundle check || bundle install --path vendor/bundle

gradle_key: &gradle_key
  jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

restore_gradle_cache: &restore_gradle_cache
  restore_cache:
    name: Restore Gradle Cache
    key: *gradle_key

save_gradle_cache: &save_gradle_cache
  save_cache:
    name: Save Gradle Cache
    key: *gradle_key
    paths:
      - ~/.gradle
      - ~/.m2

save_gems_cache: &save_gems_cache
  save_cache:
    name: Save Ruby Cache
    key: *gems_key
    paths:
      - vendor/bundle

restore_gems_cache: &restore_gems_cache
  restore_cache:
    name: Restore Ruby Cache
    key: *gems_key

gems_key: &gems_key
  gems-{{ checksum "Gemfile.lock" }}

setup_google_services: &setup_google_services
  run:
    name: Setup Google Services
    command: |
      mkdir ~/project/app/src/prodFlavor && touch ~/project/app/src/prodFlavor/google-services.json
      mkdir ~/project/app/src/stageFlavor && touch ~/project/app/src/stageFlavor/google-services.json
      echo $GOOGLE_SERVICES_PROD | base64 --decode > ~/project/app/src/prodFlavor/google-services.json
      echo $GOOGLE_SERVICES_STAGE | base64 --decode > ~/project/app/src/stageFlavor/google-services.json
      cat ~/project/app/src/stageFlavor/google-services.json

build_app: &build_app
  run:
    name: Assemble release
    command: ./gradlew clean assembleRelease

deploy_stage: &deploy_stage
  run:
    name: Deploy to stage
    command: |
      if [[( "${CIRCLE_BRANCH}" == "develop" ||  "${CIRCLE_BRANCH}" == "feature/12650/home_redesign" )]];
      then
        bundle exec fastlane alphaFlavor
      fi

deploy_production: &deploy_production
  run:
    name: Deploy to production
    command: |
      if [[ ( "${CIRCLE_BRANCH}" == "master" ) ]];
      then 
        bundle exec fastlane productionFlavor
      fi


jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
    steps:
      - checkout
      - *setup_google_services
      - *restore_gradle_cache
      - *restore_gems_cache
      - *android_dependencies
      - *ruby_dependencies
      - *save_gradle_cache
      - *save_gems_cache
      - *build_app
      - *deploy_stage
      - *deploy_production
`

**Comment by janpio** [comment]
Can you add a version output at the beginning of the "Install Ruby Dependencies" step? ("Setup Google Services" gives an indication how to make a multi line command)

**Comment by zerinasever** [comment]
Yes, it seems that it use wrong bundler version, do you know why is that? How can I setup that it use right version? And thanks a lot for your time and help Jan, I appreciate that.
![Screenshot from 2019-11-24 11-50-34](https://user-images.githubusercontent.com/45461463/69493619-0854d900-0eb1-11ea-9cdf-41a90d0124a8.png)

**Comment by janpio** [comment]
As I understand it Circle uses old bundler by default. Here is something that might help: https://webcache.googleusercontent.com/search?q=cache:TL8TPXQmHXAJ:https://discuss.circleci.com/t/using-bundler-2-0-during-ci-fails/27411+&cd=1&hl=en&ct=clnk&gl=de&lr=lang_de%7Clang_en&client=firefox-b-d

**Comment by zerinasever** [comment]
Yes, it works with this changes. Thanks a lot for your help Jan. :)

**Comment by janpio** [comment]
Can you share the final config that worked for you? Other people might find it via Google or other search engines and benefit from having a working example.

**Comment by zerinasever** [comment]
Yes, of course. 
```
version: 2

android_dependencies: &android_dependencies
  run:
    name: Install Android Dependencies
    command: ./gradlew androidDependencies

ruby_dependencies: &ruby_dependencies
  run:
    name: Install Ruby Dependencies
    command: |
      echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
      source $BASH_ENV
      gem install bundler
      bundler -v
      bundle check || bundle install --path vendor/bundle

gradle_key: &gradle_key
  jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

restore_gradle_cache: &restore_gradle_cache
  restore_cache:
    name: Restore Gradle Cache
    key: *gradle_key

save_gradle_cache: &save_gradle_cache
  save_cache:
    name: Save Gradle Cache
    key: *gradle_key
    paths:
      - ~/.gradle
      - ~/.m2

save_gems_cache: &save_gems_cache
  save_cache:
    name: Save Ruby Cache
    key: *gems_key
    paths:
      - vendor/bundle

restore_gems_cache: &restore_gems_cache
  restore_cache:
    name: Restore Ruby Cache
    key: *gems_key

gems_key: &gems_key
  gems-{{ checksum "Gemfile.lock" }}

setup_google_services: &setup_google_services
  run:
    name: Setup Google Services
    command: |
      mkdir ~/project/app/src/prodFlavor && touch ~/project/app/src/prodFlavor/google-services.json
      mkdir ~/project/app/src/stageFlavor && touch ~/project/app/src/stageFlavor/google-services.json
      echo $GOOGLE_SERVICES_PROD | base64 --decode > ~/project/app/src/prodFlavor/google-services.json
      echo $GOOGLE_SERVICES_STAGE | base64 --decode > ~/project/app/src/stageFlavor/google-services.json
      cat ~/project/app/src/stageFlavor/google-services.json

build_app: &build_app
  run:
    name: Assemble release
    command: ./gradlew clean assembleRelease

deploy_stage: &deploy_stage
  run:
    name: Deploy to stage
    command: |
      if [[( "${CIRCLE_BRANCH}" == "develop" ||  "${CIRCLE_BRANCH}" == "feature/12650/home_redesign" )]];
      then
        bundle exec fastlane alphaFlavor
      fi

deploy_production: &deploy_production
  run:
    name: Deploy to production
    command: |
      if [[ ( "${CIRCLE_BRANCH}" == "master" ) ]];
      then 
        bundle exec fastlane productionFlavor
      fi


jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
    steps:
      - checkout
      - *setup_google_services
      - *restore_gradle_cache
      - *restore_gems_cache
      - *android_dependencies
      - *ruby_dependencies
      - *save_gradle_cache
      - *save_gems_cache
      - *build_app
      - *deploy_stage
      - *deploy_production
```
