### ISSUE TITLE
Building react native ios app with fastlane hangs

### ISSUE THREAD

**Issue by lukemcgregor** [fastlane/fastlane#16080]
### Question Checklist

- [ y ] Updated fastlane to the latest version
- [ y ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ y ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ y ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description
I am trying to get a react native project to deploy to testflight using fastlane and github actions. This is a plain project created via `npx react-native init` with no modifications except for an app icon. 

The project correctly builds and deploys via `fastlane beta` on my local machine but hangs in github actions on the following:

>[03:38:26]: ▸ Running script 'Bundle React Native code and images'
>[03:38:29]: ▸     the transform cache was reset.
>[03:38:52]: ▸ Generating 'testAppPipeline.app.dSYM'

I have spent the whole day searching and trying things to resolve this but haven't been able to work it out. Most of the issues with similar hangs are around old versions ect. I have also turned off dSYM and when I do it just hangs on `the transform cache was reset.`. Locally these lines take only a couple of seconds but i've left it as long as 45 mins on github.

As far as I can tell everything is the same on my local machine as it is on the build server so I'm really lost as to why this issue is happening. If anyone has anything I should try I would love to hear.

#### Github action
```
name: CI

on: [push]

jobs:
  check:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('yarn.lock') }}
    - name: install
      run: yarn install --frozen-lockfile
  deploy:
    needs: [check]
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: fastlane update
      working-directory: ./ios
      run: sudo gem install fastlane -NV
    - name: fastlane env
      working-directory: ./ios
      run: fastlane env
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('yarn.lock') }}
    - name: pods
      working-directory: ./ios
      run: pod install
    - name: pods
      working-directory: ./ios
      run: brew install watchman
    - name: deploy to test flight
      env:
        MATCH_PASSWORD:  ${{ secrets.MATCH_PASSWORD }}
        MATCH_URL:  ${{ secrets.MATCH_URL }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      working-directory: ./ios
      run: fastlane beta
```

### Stack
| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 10.15.3                                            |
| Ruby                        | 2.7.0                                              |
| Bundler?                    | false                                              |
| Git                         | git version 2.25.0                                 |
| Installation Source         | /usr/local/lib/ruby/gems/2.7.0/bin/fastlane        |
| Host                        | Mac OS X 10.15.3 (19D76)                           |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.0/lib                   |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                        |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode_11.3.1.app/Contents/Developer/ |
| Xcode Version               | 11.3.1              
### System Locale
| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | âœ… |
| LC_ALL   | en_US.UTF-8 | âœ… |
| LANGUAGE |             |   |
### fastlane files:
`./fastlane/Fastfile`
```ruby
default_platform(:ios)
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(
      type: "appstore", 
      readonly: true,
      git_url: ENV["MATCH_URL"],
      app_identifier: "com.myapp"
      )
    increment_build_number(
      build_number: ENV["GITHUB_RUN_NUMBER"],
      xcodeproj: "testAppPipeline.xcodeproj"
    )
    get_certificates( # Create or get certificate, and install it
      output_path: "./builds" # Download certificate in the build folder (you don't need to create the folder)
    )
    get_provisioning_profile( # Create or get provisioning profile
      output_path: "./builds",  # Download provisioning profile in the build folder
      filename: "provisioning.mobileprovision" # Rename the local provisioning profile
    )
    update_project_provisioning( # Set the project provisioning profile (related in Xcode to the General > Signing Release section)
      xcodeproj: "testAppPipeline.xcodeproj",
      target_filter: "testAppPipeline", # Name of your project
      profile: "./builds/provisioning.mobileprovision",
      build_configuration: "Release"
    )
    update_project_team( # Set the right team on your project
      teamid: CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    )
    gym(
      workspace: "testAppPipeline.xcworkspace", 
      configuration: "Release",
      scheme: "testAppPipeline",
      clean: true,
      export_method: "app-store",
      output_directory: "./builds",
      output_name: "testAppPipeline.ipa",
    )
    upload_to_testflight
  end
end
```
`./fastlane/Appfile`
```ruby
app_identifier("com.myapp") # The bundle identifier of your app
apple_id("me@me.com") # Your Apple email address
itc_team_id("1234") # App Store Connect Team ID
team_id("abc") # Developer Portal Team ID
```
### fastlane gems
| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.142.0 | âœ… Up-To-Date  |
**No plugins Loaded**
<b>Loaded gems</b>
| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| uri                       | 0.10.0       |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| json                      | 2.3.0        |
| bundler                   | 2.1.4        |
| forwardable               | 1.3.1        |
| logger                    | 1.4.2        |
| cgi                       | 0.1.0        |
| timeout                   | 0.1.0        |
| stringio                  | 0.1.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.2.0        |
| strscan                   | 1.0.3        |
| date                      | 3.0.0        |
| delegate                  | 0.1.0        |
| fileutils                 | 1.4.1        |
| zlib                      | 1.1.0        |
| singleton                 | 0.1.0        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| racc                      | 1.4.16       |
| rexml                     | 3.2.3        |
| open3                     | 0.1.0        |
| yaml                      | 0.1.0        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
