### ISSUE TITLE
Improvement to documentation please....

### ISSUE THREAD

**Issue by NBroomfield** [fastlane/fastlane#18750]
### Issue Description
Neither https://docs.fastlane.tools/app-store-connect-api/ nor here https://docs.fastlane.tools/actions/app_store_connect_api_key/ adequately explain where the key file needs to be store, what directory? In the Fastlane folder? in the root of the project?

**Comment by crazymanish** [comment]
Hello @NBroomfield 

You can **store key file anywhere** and you just need to provide the correct Key file path. 😇
See for example: https://docs.fastlane.tools/app-store-connect-api/#using-fastlane-api-key-json-file

<img width="988" alt="Screenshot 2021-05-26 at 18 06 59" src="https://user-images.githubusercontent.com/5364500/119694589-a4b4be80-be4d-11eb-9612-8c6be1401a97.png">

**Comment by isaacressler** [comment]
I'm having the same issue trying to figure out where to store the file. Apple says [not to include it in your code repository](https://developer.apple.com/documentation/appstoreconnectapi/creating_api_keys_for_app_store_connect_api), however that appears to be what fastlane is suggesting. It would be nice if this was explicitly stated, and if storing it with the code is Fastlane's solution include the reason why this is recommended despite Apple's instructions.

**Comment by NBroomfield** [comment]
@isaacressler Glad it's not just me :-D

Do you know where the path is supposed to be relevant to? I've tried the Fast lane folder and the root folder (e.g. ios/Fastlane/key file.p8) but it just keeps saying file cannot be found?

**Comment by John-Goldman** [comment]
I'm having the same issue attempting to figure out where to store the record. Do you know where the way is assumed to be relevant to?
[my gift card site](https://www.mygiftcardsite.bid/)

**Comment by bdolewski** [comment]
I use GitLab and I solved it using GitLab vault/secret. So my `fastlane` configuration expects API key being placed at path X but there is no file committed here in the repo. It's placed there by CI during build. You need to figure out how to do it on your CI of choice.

**Comment by bdolewski** [comment]
That's the `.gitlab-ci.yml`. Maybe it will clear some things out:
```
deploy_to_test_flight:on-schedule:
    dependencies: []
    stage: deploy
    script:
      - NUM_COMMITS=$(git log  --format=%an --since='24 hours ago' | grep -vE 'GitLab' | wc -l)
      - if [ "$NUM_COMMITS" == 0 ]; then exit 0; fi
      - echo "There are changes on given branch - will deploy a new build"
      - mv $Auth_KEY_p8 fastlane/Auth_KEY.p8
      - git remote rm origin && git remote add origin git@${CI_SERVER_HOST}:${CI_PROJECT_PATH}.git
      - fastlane run reset_simulator_contents
      - fastlane deploy_INTEGRA
      - git push --tags git@${CI_SERVER_HOST}:${CI_PROJECT_PATH}.git HEAD:${CI_COMMIT_REF_NAME}
```
