### ISSUE TITLE
[Match] No value found for 'git_url'

### ISSUE THREAD

**Issue by geeklingo** [fastlane/fastlane#20790]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Using fastlane to build and deploy an XCode project (exported from Unity). When match is run, the following error is received:

`No value found for 'git_url'`

##### Command executed

bundle exec fastlane match

Running the command on my local machine works fine but when running via GitLab i keep getting that error. The git_url is in my matchfile which is in my fastlane folder. It all works as it runs locally fine. Just not remotely via the CI\CD pipeline. I'm not using environment variables for this.

The relevant section from my gitlab-ci.yml
```
deploy-ios:
 stage: deploy
 script:
   - cd $UNITY_DIR/Builds/iOS/$BUILD_NAME
   - bundle update
   - bundle exec fastlane match <- This is where it's failing
   - bundle exec fastlane run set_info_plist_value path:"./Info.plist" key:"CFBundleShortVersionString" value:"0.1.0"
   - bundle exec fastlane ios beta
 tags:
   - ios
   - mac
 needs: ["build-ios-xcode"]
 # Only deploy if "deploy" is in the tag
 rules:
   - if: '$CI_COMMIT_TAG =~ /^deploy.*/i'
```

Matchfile
```
git_url("https://gitlab.com/xxxx/xxxx")
storage_mode("git")

type("appstore") # The default type, can be: appstore, adhoc, enterprise or development
app_identifier(["bundleid"])
username("username") # Your Apple Developer Portal username

type("development") # The default type, can be: appstore, adhoc, enterprise or development
app_identifier(["bundleid"])
username("username") # Your Apple Developer Portal username
```
