### ISSUE TITLE
trivy scan reports api key leak in test key fewfawefawfe

### ISSUE THREAD

**Issue by childnode** [fastlane/fastlane#21096]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`HIGH: AsymmetricPrivateKey (private-key)` finding in `fastlane/lib/fastlane/actions/app_store_connect_api_key.rb:138`

for unseen reasons, this is not in test code but in release code!

<details>

```
HIGH: AsymmetricPrivateKey (private-key)
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Asymmetric Private Key
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 libexec/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/app_store_connect_api_key.rb:138
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 136               key_id: "D83848D23",
 137               issuer_id: "227b0bbf-ada8-458c-9d62-3d8022b7d07f",
 138 [             key_content: "-----BEGIN EC PRIVATE KEY-----****************-----END EC PRIVATE KEY-----"
 139             )'
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
</details>

nasty to exclude this via 

`trivy-secret.yaml`
```yaml
---
allow-rules:
  - id: fastlane-test-keys
    description: |
      Fastlane (external dependency) uses test keys
      causing a false positive
    path: ^.*\/fastlane-[\d\.]+\/fastlane\/lib\/fastlane\/actions\/app_store_connect_api_key.rb
```

##### Command executed

`trivy fs /opt/homebrew/Cellar/fastlane/*`

https://aquasecurity.github.io/trivy/v0.33/docs/secret/scanning/

### Environment

trivy
