### ISSUE TITLE
Distribute ipa to hockeyapp using circleci

### ISSUE THREAD

**Issue by tariq235** [fastlane/fastlane#3870]
I would like get rid off from shenzhen command completely. What is the best way to distribute to hockey using circle.yml+fastlane ?

my yml file 

```
machine:
  environment:
    XCODE_SCHEME: APPNAME
    DEVELOPER_NAME: 'iPhone Developer: Tariq Mohammad (XXXXXX)'

dependencies:
  override:
    - sudo gem install shenzhen
test:
  override:
    - scan --scheme $XCODE_SCHEME --device "iPhone 6s" --clean

deployment:
  hockey:
    branch: development
    commands:
      - ./scripts/add-key.sh
      - gym --scheme $XCODE_SCHEME --codesigning_identity $DEVELOPER_NAME -c Debug
      - ipa distribute:hockeyapp -m "bug fixes" --token $HOCKEYAPP_TOKEN
```
