### ISSUE TITLE
Feature: Matchfile Matrix

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/fastlane#4100]
It is slow and very cumbersome to fetch a bunch of certificates via match, take this example for setting up certificate for a iOS and Watch App for Development, Ad-Hoc and App Store:

``` ruby
match(app_identifier: "com.forever-beta.sup", type: "development")
match(app_identifier: "com.forever-beta.sup.watchkitapp", type: "development")
match(app_identifier: "com.forever-beta.sup.watchkitapp.watchkitextension", type: "development")
match(app_identifier: "com.forever-beta.sup", type: "adhoc")
match(app_identifier: "com.forever-beta.sup.watchkitapp", type: "adhoc")
match(app_identifier: "com.forever-beta.sup.watchkitapp.watchkitextension", type: "adhoc")
match(app_identifier: "com.forever-beta.sup", type: "appstore")
match(app_identifier: "com.forever-beta.sup.watchkitapp", type: "appstore")
match(app_identifier: "com.forever-beta.sup.watchkitapp.watchkitextension", type: "appstore")
```

Each time, Match has to clone the repo, decrypt and install. Additionally if I want to renew these manually I have to enter the commands in one by one.

So what I would like to prepose some kind of matrix for the matchfile, so I could do this:

``` ruby
git_url "git@github.com:Repo/certificates.git"

matrix :types => ["development", "adhoc", "appstore"] do
app_identifier  "com.forever-beta.sup"
app_identifier  "com.forever-beta.sup.watchkitapp"
app_identifier  "com.forever-beta.sup.watchkitapp.watchkitextension""
end


# app_identifier "tools.fastlane.app"
# username "user@fastlane.tools" # Your Apple Developer Portal username

# For all available options run `match --help`
# Remove the # in the beginning of the line to enable the other options
```

With this I could run `match` to generate all my certificates at once for all types as well as do the same in fastlane.

Match would only need to clone and decrypt the repo once when in read-only mode and in write mode it would save me having to type all the individual commands.

**Comment by TKBurner** [comment]
Thanks @jcampbell05! Great to hear from you again. This is a very interesting use case. I'll be sure the team takes a look.  :+1:

**Comment by KrauseFx** [comment]
Looking at this, it seems more complicated for non-Ruby developers, don't you think?

**Comment by sjrmanning** [comment]
+1 for this or something like it! With a WatchKit app component, we're finding match takes so long as we need to cycle through match for the main app ID, the WatchKit app ID and finally the WatchKit extension ID. We're using `match` with `fastlane` and for each ID all settings are the same apart from the ID, but because they run as separate match processes it has to clone, decrypt, validate, etc. all over again for each ID.

**Comment by jcampbell05** [comment]
@KrauseFx Yes I think so but even having some sort of YAML file with all of the certificates for the project would be great:

```yaml
appstore:
    - com.forever-beta.sup
    - com.forever-beta.sup.watch
    - com.forever-beta.sup.watch.watchkitextension
adhoc:
    - com.forever-beta.sup
    - com.forever-beta.sup.watch
    - com.forever-beta.sup.watch.watchkitextension
developer:
    - com.forever-beta.sup
    - com.forever-beta.sup.watch
    - com.forever-beta.sup.watch.watchkitextension
```
