### ISSUE TITLE
How to pass password in circleci yml ?

### ISSUE THREAD

**Issue by tariq235** [fastlane/fastlane#4137]
My YML File

```
machine:
  environment:
    XCODE_SCHEME: APPNAME
    DEVELOPER_NAME: 'iPhone Developer: Tariq Mohammad (XXXXXXX)'

  xcode:
    version: "7.3"

general:
  build_dir: APPNAME

test:
  override:
    - scan --workspace APPNAME.xcworkspace --scheme APPNAME --device "iPhone 6s" --clean

deployment:
  hockey:
    branch: tempTestflightDebug
    commands:
      - ./scripts/add-key.sh
      - pilot upload -c Debug --username "tariq@gmail.com" --password $FASTLANE_PASSWORD

```

where FASTLANE_PASSWORD is stored in circleci environment settings.
This is throwing me following error -
```
pilot upload -c Debug --username "tariq@gmail.com" --password $FASTLANE_PASSWORD
invalid option: --password

pilot upload -c Debug --username "tariq@gmail.com" --password $FASTLANE_PASSWORD returned exit code 1

Action failed: pilot upload -c Debug --username "tariq@gmail.com" --password $FASTLANE_PASSWORD

```

Earlier when i tried only pilot upload -c Debug --username "tariq@gmail.com"
then it was stuck at the following -

```
pilot upload -c Debug --username "tariq@gmail.com"
[21:42:51]: Login to iTunes Connect (tariq@gmail.com)
-------------------------------------------------------------------------------------
The login information you enter will be stored in your Mac OS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` env variable
More information about it on GitHub: https://github.com/fastlane/credentials_manager
-------------------------------------------------------------------------------------
Password (for tariq@gmail.com): 

```

How should i pass the password using the `FASTLANE_PASSWORD` env variable ? I have tried using circleci env variable but looks like it didn't worked ? Anything I am missing in my circleci yml file ?
